.TH PROXY_REMOTE 1 "February 25, 2013"
.SH NAME 
proxy_remote \- server-side component of coded tcp proxy 
.SH SYNOPSIS
.B proxy_remote 
.RI [ options ] " action" ...
.SH DESCRIPTION
Binds to port and address on server and listens for incoming connections from
.B proxy_local
These are forwarded to appropriate port on server for service, and any response is sent back via 
.B proxy_remote
to 
.B proxy_local
and so to client machine. See
.B man ctcp(1)
for further details of how to configure proxy_local and proxy_remote to work together.
.SH ACTIONS
.TP
.B start
Start daemon
.TP 
.B shutdown
Shutdown daemon
.SH OPTIONS
.TP
.B \-h, \-\-help
Display help screen and exit
.TP
.B \-v, \-\-version
Show version of program.
.TP
.B \-c file, \-\-config file
Use configuration file 'file'.  Default is /etc/ctcp/proxy_remote.conf
.TP
.B \-f, \-\-forceload
Force starting of daemon even if PID file exists
.SH FILES
.TP
.B /etc/ctcp/proxy_remote.conf
The system-wide configuration file.
.TP
.B /var/run/proxy_remote.pid
Process ID lock file to avoid multiple copies of running simultaneously.
.SH SEE ALSO
.B proxy_local(1),
.B ctcp(1)
