#!/usr/bin/python
import sys
import matplotlib.pyplot as plt
import math

def main(args):

    times = []
    instant_BW = []
    average_BW = []

    mss = 1472
    current= 0.1
    res = 0.1
    abw = 0
    bw = 0

    f = open(args[0], 'r')
    for line in f:
        values = line.split(" ")


        if values[-1] == "xmt\n":
            # The variable values is a list of the form
            # [time, segment, xmt]

            abw += mss
            bw += mss

            time = float(values[0])

            if time > current and time <= (current + res):
                times.append(time)

                instant_BW.append(8e-6*bw/res)
                average_BW.append(8e-6*1.0*abw/current)

                current = res + current
                bw = 0
            elif time > (current + res):
                zero_point = res*math.floor(time/res)
                times.append(current)
                times.append(zero_point)

                instant_BW.append(0)
                instant_BW.append(0)

                average_BW.append(8e-6*1.0*abw/current)
                average_BW.append(8e-6*1.0*abw/zero_point)

		current = zero_point + res
		bw = 0





#   print average_BW
    plt.plot(times, instant_BW, 'r--', times, average_BW, 'g--')
    plt.xlabel('time')
    plt.ylabel('Mbs')
    plt.show()


if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.exit("Usage: ./grapher <ctcpsrv_output>")
    main(sys.argv[1:])

